export const themeMapping: Record<string, string> = {
  // Macro Outlook
  "BASE CASE": "Macro Outlook",
  "GROWTH": "Macro Outlook",
  "RECESSION": "Macro Outlook",
  "SLOWDOWN": "Macro Outlook",
  "SOFT LANDING": "Macro Outlook",
  "STAGFLATION": "Macro Outlook",
  "RISKS": "Macro Outlook",
  "VOLATILITY": "Macro Outlook",
  "UNEMPLOYMENT": "Macro Outlook",

  "INFLATION": "Inflation & Prices",
  "DISINFLATION": "Inflation & Prices",
  "WAGES": "Inflation & Prices",

  "MONETARY POLICY": "Monetary Policy",
  "PIVOT": "Monetary Policy",
  "RATE CUTS": "Monetary Policy",
  "TIGHTENING": "Monetary Policy",
  "QUANTITATIVE EASING": "Monetary Policy",
  "QUANTITATIVE TIGHTENING": "Monetary Policy",
  "HIGH RATES": "Monetary Policy",
  "INTEREST RATES": "Monetary Policy",
  "LIQUIDITY": "Monetary Policy",
  "NEGATIVE RATES": "Monetary Policy",

  "FISCAL": "Fiscal Policy",
  "STIMULUS": "Fiscal Policy",

  "STOCKS": "Equities",
  "COMPANIES": "Equities",
  "EARNINGS": "Equities",
  "VALUATIONS": "Equities",
  "CYCLICALS": "Equities",
  "SECTORS": "Equities",
  "QUALITY": "Equities",
  "ROTATION": "Equities",
  "STOCK PICKING": "Equities",
  "MAGNIFICENT 7": "Equities",
  "TECH": "Equities",
  "RALLY": "Equities",

  "BONDS": "Fixed Income",
  "CREDIT": "Fixed Income",
  "YIELDS": "Fixed Income",
  "SPREADS": "Fixed Income",
  "DURATION": "Fixed Income",
  "DEFAULTS": "Fixed Income",
  "REFINANCING": "Fixed Income",
  "BOND SUPPLY": "Fixed Income",
  "INCOME": "Fixed Income",
  "STEEPENING": "Fixed Income",

  "CURRENCIES": "Currencies",
  "DOLLAR": "Currencies",

  "COMMODITIES": "Commodities",
  "METALS": "Commodities",
  "ENERGY": "Commodities",

  "ALTERNATIVE ASSETS": "Alternatives",
  "REAL ESTATE": "Alternatives",
  "PRIVATE MARKETS": "Alternatives",
  "HEDGE FUNDS": "Alternatives",

  "MULTI ASSET": "Multi-Asset",
  "DIVERSIFICATION": "Multi-Asset",
  "HEDGING": "Multi-Asset",
  "RETURNS": "Multi-Asset",

  "US": "Regions",
  "UK": "Regions",
  "EUROPE": "Regions",
  "CHINA": "Regions",
  "ASIA": "Regions",
  "APAC": "Regions",
  "GLOBAL": "Regions",
  "JAPAN": "Regions",

  "AI": "Thematic",
  "ESG": "Thematic",
  "WAR": "Thematic",
  "GEOPOLITICS": "Thematic",
  "POLITICS": "Thematic",
  "ELECTIONS": "Thematic",
  "REGULATION": "Thematic",
  "RESHORING": "Thematic",
  "SUPPLY CHAIN": "Thematic",
  "TARIFFS": "Thematic",
  "TRADE": "Thematic",
  "COVID": "Thematic",
  "BREXIT": "Thematic",
  "CONSUMERS": "Thematic"
};
